on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types:
      - completed

name: slack-check-package

jobs:
  message-slack:
    if: ${{ github.event.workflow_run.event == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ“¥ Download status artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh run download ${{ github.event.workflow_run.id }} --dir status

      - name: ðŸ§° Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: ðŸ“¢ Send Slack message
        env:
          GITHUB_PAT: ${{ secrets.PRIVATE_ACTIONS_PAT_2 }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          install.packages("remotes")
          remotes::install_github("poissonconsulting/poisslack")

          files <- list.files("status", pattern = "\\.txt$", full.names = TRUE, recursive = TRUE)
          print(files)

          msg <- paste(basename(Sys.getenv("REPO")), "R CMD check results:\n\n")
          for (i in files) {
            os <- basename(i)
            os <- sub("\\.txt$", "", os)
            os <- gsub("-", " ", os)

            status <- readLines(i)
            status <- status[length(status)]

            if (grepl("[1-9][0-9]* error", status)) { status <- "âŒ ERROR" }
            else if (grepl("[1-9][0-9]* warning", status)) { status <- "âš ï¸ WARNING" }
            else if (grepl("[1-9][0-9]* note", status)) { status <- "ðŸ“ NOTE" }
            else { status <- "âœ… SUCCESS" }

            msg <- paste0(msg, os, ": ", status, "\n")
          }
          msg <- paste0(msg, "\nðŸ”— View full logs: ", Sys.getenv("URL"))

          poisslack::slackr_bot(
            text = msg,
            channel = basename(Sys.getenv("REPO")),
            username = "check-package-bot",
            incoming_webhook_url = Sys.getenv("SLACK_WEBHOOK_URL")
          )
        shell: Rscript {0}
